Rewrite to use FastAPI instead
eiffel-community/etos-api pull request #13
Opened 2020-11-12 11:31 UTC by t-persson

### Applicable Issues

fixes: eiffel-community/etos#64
fixes: eiffel-community/etos#65

### Description of the Change

Rewrite ETOS API to use FastAPI instead.

### Alternate Designs

There are other frameworks. This one caught my eye as being simple to understand.
It also boasts being very fast in combination with uvicorn.

### Benefits

Faster API, cleaner structure and a way forward to using the ETOS API as the sole external API in ETOS.

### Possible Drawbacks

FastAPI uses asyncio which is not supported everywhere in ETOS. This is mitigated with a sync_to_async function.
This change also uses libraries that conflict with ETOS Library.

### Sign-off

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

Signed-off-by: Tobias Persson <tobias.persson@axis.com>

2020-11-13 09:42 UTC, andjoe-axis approved these changes
+1

2020-11-16 14:05 UTC, fredjn requested changes

2020-11-17 07:38 UTC, t-persson commented on tests/test_routers.py
> +
Done

2020-11-17 07:38 UTC, t-persson commented on tests/test_routers.py
> +            - HEAD on root shall return 204.
Done

2020-11-17 07:38 UTC, t-persson commented on src/etos_api/library/graphql.py
> +                assert response["artifactCreated"]["edges"]
Done

2020-11-23 09:18 UTC, fredjn approved these changes

2020-11-24 06:00 UTC, merged

2020-11-24 06:12 UTC, nordixinfra reviewed
- Build Status: **SUCCESS**
- Build URL: [Nordix Jenkins](https://jenkins.nordix.org/job/etos-api-build-merge-ubuntu2004-master/1/)
- Command to pull image:
    `docker pull registry.nordix.org/eiffel/etos-api:dev`
    or
    `podman pull registry.nordix.org/eiffel/etos-api:dev`