Add a new API for listing logs and artifacts from a log area
eiffel-community/etos-api pull request #66
Opened 2024-06-04 09:43 UTC by t-persson

### Applicable Issues

eiffel-community/etos#238

### Description of the Change

Added a v1alpha API for listing logs and artifacts produced by ETOS. This is to be used to reduce the load of the event repositories when ETOS executes many testruns.

### Alternate Designs

I thought about proxying the files directly from the API and have the client always know how to download the files. I decided against it due to the added complexity and not wanting to deal with memory usage in the logarea service. This is something that may be looked at in a v1 release of the API.

### Possible Drawbacks

This API service will get a lot of traffic instead of the event repository. However I do believe that this solution is more scalable than the Eiffel GraphQL API.

### Sign-off

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

Signed-off-by: Tobias Persson <tobias.persson@axis.com>

2024-06-10 07:24 UTC, t-persson commented
This change works if the changes in #65 are merged. All CI problems are for python code and I have not changed any python code

2024-06-14 11:57 UTC, fredjn requested changes

2024-06-18 05:23 UTC, t-persson commented on pkg/logarea/v1alpha/logarea.go
> +	w.WriteHeader(http.StatusNoContent)
It tells clients to not try to infer the content type by parsing the output. It is used for security, but it also helped with another case where the browser borked the API response for me.
I added the header to the other handler as well.

2024-06-18 05:25 UTC, t-persson commented on pkg/logarea/v1alpha/logarea.go
> +	response, err := h.client.Get(ctx, fmt.Sprintf("/testrun/%s/suite", identifier), clientv3.WithPrefix())
The only assumption I see is that the `identifier` you pass to the API is the same identifier used for `/testrun`. I believe that this is a fair assumption.

2024-06-18 05:27 UTC, t-persson commented on test/testconfig/testconfig.go
> +	return "etcd-client:2379"
There are no tests using it and we will need to mock ETCD for the tests so the return value of this function does not really matter.

2024-06-20 08:56 UTC, fredjn approved these changes

2024-06-20 09:40 UTC, merged