Add Github publishing workflow for etos-iut
eiffel-community/etos-api pull request #74
Opened 2024-09-17 14:37 UTC by andmat900

### Applicable Issues
- https://github.com/eiffel-community/etos/issues/261
 
### Description of the Change

This change adds a Github workflow to publish ETOS IUT Provider images in the same way as it is done for Log Area Provider and SSE.

### Alternate Designs

### Possible Drawbacks

### Sign-off

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

Signed-off-by: Andrei Matveyeu, andrei.matveyeu@axis.com

2024-09-20 07:58 UTC, t-persson requested changes

2024-09-20 07:58 UTC, t-persson commented on .github/workflows/build-push.yml
> +      logAreaVersion: ${{ steps.image.outputs.version }}
Should not output logAreaVersion

2024-09-20 07:58 UTC, t-persson commented on .github/workflows/build-push.yml
> +    outputs:
This workflow should update the manifest as well right? Add it in the "Update manifests" below

2024-09-25 08:12 UTC, fredjn approved these changes

2024-09-25 08:24 UTC, merged